name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "v*.*.*"
    paths-ignore:
      - LICENSE
      - "*.md"
      - .vscode
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          ./scripts/install-ubuntu.sh
          # assert no library missing
          test $(ldd $(which gpclient) | grep 'not found' | wc -l) -eq 0

  snapshot-archive-all:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all

      - name: Archive all
        run: |
          ./scripts/snapshot-archive-all.sh

      - name: Verify debian package
        run: |
          ./scripts/verify-debian-package.sh

      - uses: actions/upload-artifact@v2
        with:
          name: snapshot-source-code
          path: ./artifacts/*

  release-archive-all:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all

      - name: Archive all
        run: |
          ./scripts/release-archive-all.sh

      - name: Verify debian package
        run: |
          ./scripts/verify-debian-package.sh

      - uses: actions/upload-artifact@v2
        with:
          name: release-source-code
          path: ./artifacts/*

  release-github:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-source-code
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/*.tar.gz
